"""New revision: Auto generate revision.

Revision ID: a99a1414be53
Revises: 
Create Date: 2019-01-15 13:21:37.115674

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a99a1414be53'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('invites',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('owner_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('guest_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('guest_type', sa.Enum('TEACHER', 'STUDENT', name='guesttype'), nullable=False),
    sa.Column('status', sa.Enum('TEACHER', 'STUDENT', name='guesttype'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('invites')
    # ### end Alembic commands ###
